---
- hosts: default
  sudo: yes
  tasks:
    - name: install python pkgs
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - python-dev
        - python-pip
        - python-virtualenv

    - name: install postgres/postgis pkgs
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - postgresql
        - libpq-dev
        - libjpeg-dev
        - libgeos-c1
        - libgdal-dev
        - postgis
        - postgresql-9.3-postgis-2.1-scripts
        - python-psycopg2

    - name: create db
      sudo_user: postgres
      postgresql_db: name=dcbikelanegraffiti
                     owner=vagrant
                     encoding='UTF-8'
                     template='template0'

    - name: enable postgis
      sudo_user: postgres
      postgresql_ext: name={{ item }} db=dcbikelanegraffiti
      with_items:
        - postgis
        - postgis_topology

    - name: setup virtualenv
      sudo: no
      pip: requirements=/vagrant/requirements.txt virtualenv=~/venv
